### PR TITLE
Add Feedback Form Button

### PR DESCRIPTION
**Pull request by hoffmabc**
Ok here's a feedback mechanism using Doorbell.io

What it looks like:
image

image

### CODE REVIEW

**Comment by hoffmabc** [comment]
We can also customize this if desired @jjeffryes

**Comment by rmisio** [comment]
> We can also customize this if desired @jjeffryes

There's also an [API](https://doorbell.io/docs/api) in case the customization doesn't allow us to do something we want.

**Comment by rmisio** [comment]
@jjeffryes This one LGTM.

@hoffmabc FWIW, most of the PRs seem to fail Travis with at least a couple different reasons.

**Comment by jjeffryes** [comment]
@hoffmabc did you want to update this so it passes Travis, or did you want someone else to look at that?

**Comment by hoffmabc** [comment]
OK I will fix the issues.

**Comment by rmisio** [comment]
@jjeffryes I don't think we can wait on Travis. It's been failing for weeks for non lint / test reasons. Anyhow, I can confirm this PR passes both lint and test, so if it looks good to you, please merge.

**Pull request merged**
