### PR TITLE
add ISO 4217 code in list of currencies

### PR DESCRIPTION
**Pull request by klaha707**
Fix regarding issue #1032

### CODE REVIEW

**Comment by morebrownies** [comment]
I'm a bit confused on the question @rmisio. Should the code be in the UI? I'm not sure what that means.

**Comment by rmisio** [comment]
@morebrownies Should the currency drop downs include the code as well as the name, e.g. 'United States Dollar (USD)' instead of just 'United States Dollar'?

**Comment by rmisio** [comment]
> I'm not sure if adding the codes in the template is the right place to do it. That could be an issue for languages where the code should not be in parenthesis or should be on the left instead of the right.

@klaha707 I echo these concerns. Would you mind having it driven by a translation string?

```
// en_US.json
"currencyPairing": "%{convertedCurValue} (%{baseCurValue})",
"currencyWithCode": "%{name} (%{code})",
```

I also think it would make sense to centralize this in the currency module rather than every template having to implement it.

```
// data/currencies.js in getTranslatedCurrencies()
  let translated = currencies.map(currency => {
    const name = app.polyglot.t(`currencies.${currency.code}`);
    return {
      ...currency,
      name,
      nameWithCode: app.polyglot.t('currencyWithCode', {
        name,
        code: currency.code,
      }),
    };
  });

// there's also a second section a few lines down in that method
// where the nameWithCode would need to be similarly worked in
```

**Comment by klaha707** [comment]
Sounds like a better solution with a translation string. That the format of the code could be language specific didn't really cross my mind. Thanks for all the feedback.

**Comment by jjeffryes** [comment]
@klaha707 were you planning to make revisions to this PR based on the comments we made, or should I close it?

**Comment by rmisio** [comment]
@klaha707 We're going to close this one for now. If you get back to it and incorporate the suggested changes, feel free to re-submit.

**Pull request closed without merging**
