### PR TITLE
Build Verify Script

### PR DESCRIPTION
**Pull request by hoffmabc**
This pull request has several components.

1) generateHashes.sh -
This script is for the build maintainer (currently @hoffmabc) to generate hashes and signature file for each release. This file will then be placed at https://openbazaar.org/releases/SHA256SUMS.{version}.asc for future verification.

2) verifyBinaries.sh - 
This script will download the asc hash file and gpg verify that the binaries match their hashes.

### CODE REVIEW

**Comment by rmisio** [comment]
@hoffmabc This is a 5 month old PR. What action is this waiting on and from who?

**Comment by hoffmabc** [comment]
I'll have to take a look at this to see if it still works properly.

**Comment by jjeffryes** [comment]
@hoffmabc did you ever check to see if this is still a valid PR?

**Comment by hoffmabc** [comment]
Nope. :) I will try to get to this today or tomorrow.

**Comment by hoffmabc** [comment]
@rmisio @jjeffryes this one looks good. Just retested it and everything works swimmingly.

**Comment by rmisio** [comment]
@hoffmabc Awesome turn-around time on this one!

**Pull request merged**
