### PR TITLE
Linux And Windows Tray Icons

### LINKED ISSUE #829: Cosmethic Issue: Tray Icon looks as doubled in Gnome tray bar
Brief Description: On application start, tray icon looks strange as in attached image

Operating System (OS and version):  Arch Linux
OpenBazaar version (shown on `About OpenBazaar` page in menu):  2.0.11-git
Gnome version: 3.24.2 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always I think

Steps to reproduce:
1. Install the package
2. Start the app

Additional info (links, images, etc go here):
Gnome tray

 And a question: will defaultListing.png be added? because for now debug console shows a missing image and I could open another issue

### PR DESCRIPTION
**Pull request by jjeffryes**
This is branched from #1092, to update the code for our linting rules, and make the same fix for Windows.

This closes #829 and fixes a problem in Windows where the icon was squashed, greyscale and low quality, due to using the non-square icon file for Mac.

Note: the ideal would be to have a multi-size ico file for Windows, with icon files in it for each major display size, but that would be more effort than using this single png file for small gain in quality.

### CODE REVIEW

**Comment by jjeffryes** [comment]
@SamPatt or @M0Rf30  can you confirm this still works to fix the issue with the icon on Linux?

**Comment by M0Rf30** [comment]
@jjeffryes issue is still present and is dued to this diff with my patch
```   // put logic here to set tray icon based on OS
-  if (process.platform === 'linux') {
-    var osTrayIcon = 'icon.png';
-  } else {
-    var osTrayIcon = 'openbazaar-mac-system-tray.png';
-  }
-  
+  let osTrayIcon = 'openbazaar-win-system-tray.png';
+  if (process.platform === 'darwin') osTrayIcon = 'openbazaar-mac-system-tray.png';
+
   trayMenu = new Tray(`${__dirname}/imgs/${osTrayIcon}`);
```

**Comment by jjeffryes** [comment]
@M0Rf30 weird. openbazaar-win-system-tray.png is the same as icon.png, other than being smaller. It's being used for everything except darwin, so Linux should be using it too.

**Comment by jjeffryes** [comment]
@M0Rf30 I've updated the PR so the icon being used is the same as icon.png (just named differently), can you try it again and let me know if a) the color icon is being used and b) if the doubling issue still happens?

**Comment by M0Rf30** [comment]
I'll try in minutes. Error is in my latest commit. It requires 
```icon: process.platform === 'linux' && `${__dirname}/imgs/icon.png````
I've seen this fix also on caprine app (an app for facebook on linux)

**Comment by M0Rf30** [comment]
Still error, I've also restarted my graphical session (to avoid caching error) and nothing. As informational, I use this commit be6fc2ccb2b9ebdf9b8c211241f57d234080f5b1 patch on Arch Linux packaging and everything works

**Comment by jjeffryes** [comment]
> It requires
icon: process.platform === 'linux' && `${__dirname}/imgs/icon.png

@M0Rf30 are you saying it only works on linux if the file is called icon.png?

**Comment by M0Rf30** [comment]
@jjeffryes  no only if this line contain ```platform === ...```

**Comment by jjeffryes** [comment]
@M0Rf30 that part is hard to understand. That icon should be set there for all OSes, not just Linux. What that line does is stop the icon from working for non-Linux OSes, it shouldn't change anything for Linux.

**Comment by M0Rf30** [comment]
Sorry my fault, I've checked other things and found that with NODE_ENV to devel (with debug console) it gives this issue. I'll try to rebuild iconLinux in second with no developement envs. Only a moment...

**Comment by M0Rf30** [comment]
It works 💃

**Pull request merged**
