### PR TITLE
[WIP] Auto-Updates

### PR DESCRIPTION
**Pull request by hoffmabc**
This is a working branch for code related to the auto-updating feature for the application. The objective would be to incorporate this with @rmisio refactoring of main.js and anything else that will be changed before release.

Changes:
- [x] Add autoUpdater code for OS X 
- [x] Add autoUpdater code for Windows
- [x] Send IPC calls to the rendering process instead of brute-forcing console.log and CSS manipulation in that process
- [ ] Handle IPC messages in the views and display update alerts to user
- [x] Set up squirrel server for 2.0
- [x] Install SSL certificate and DNS for squirrel server

### CODE REVIEW

**Comment by rmisio** [comment]
@jjeffryes This one looks OK from my end. There are a few minor changes that might conflict with the connect branch I'm working on, but I'll rectify those when my branch is ready to be merged.

**Comment by hoffmabc** [comment]
I'm thinking that this is probably ok to push once we work out the merge issues as you will want to handle the recipient ipc calls to the render view and show the user the update UI @rmisio

**Comment by rmisio** [comment]
@hoffmabc Sorry, just realized this was a WIP.

Anyhow, trying to clean up some PRs and I did integrate this in it's current state into #206. For any future changes, can we just open a new PR?

**Comment by hoffmabc** [comment]
Do we have a problem with this PR @rmisio I just realized we never merged this.

**Comment by rmisio** [comment]
@hoffmabc I just merged in master and worked through a lot of conflicts. Do you want to give this one another test to make sure I didn't mess anything up?

**Comment by rmisio** [comment]
This code was already merged into master.

**Pull request closed without merging**
