### PR TITLE
Create uk-UA.json

### PR DESCRIPTION
**Pull request by 6025c7**
Initial translation

### CODE REVIEW

**Comment by jjeffryes** [comment]
Does this translation exist in transifex? 

If so, please just translate it there. We pull all the translations from transifex every release, and replace any files in the repo with them.

**Comment by 6025c7** [comment]
Okay, thanks for a reply

**Comment by jjeffryes** [comment]
I saw your join request on Transifex and approved it. Thank you for helping with translations.

**Comment by 6025c7** [comment]
My pleasure!

**Pull request closed without merging**
