### PR TITLE
Various bugs

### LINKED ISSUE #183: If you click Add Shipping Option and then change to Digital Good you can't save it
Brief Description: If I Create Listing using defaults and choose add shipping option, when I change the listing type to Digital good or Service, I cannot save as the Shipping Option still shows with failed validation but is disabled and I can't access it.

Operating System (OS and version): OSX 
OpenBazaar version (shown on `About OpenBazaar` page in menu):  Commit e0a54980b8c38e8b202c8b464df698f0307976fd on origin/master

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Create Listing
2. Enter title and price and one image
3. Click Add under Shipping
4. Change Type to Digital Good
5. Click Save

Observed Behavior: Can't save the listing

Expected Behavior: Shipping Option should go away and not fail the validation.

Additional info (links, images, etc go here):

image

### LINKED ISSUE #190: When viewing your own Profile client retrieves profile via IPNS
Instead of retrieving your own profile data directly the client retrieves the profile data from the IPNS call, which results in stale data when updating your avatar and other information.

image

1) Change avatar in Settings -> Page
2) Save
3) View your page
4) Ctrl+r or Cmd+r refresh the page

Avatars will then revert to the previous settings.
image

### LINKED ISSUE #195: Bug: New listings aren't displaying in the Store page
I can create a new listing in the client and it saves correct... ie:

- The server correctly saves the listings
- I can retrieve the newly created listing by hitting the API directly
- The client even says that it saves, and when I click the bottom notification to view the listing, it shows the listing

*BUT*... when I go to the store page, the listing isn't there.

### PR DESCRIPTION
**Pull request by rmisio**
- closes #195 
- closes #190 
- closes #183 
- fixes this [issue](https://github.com/OpenBazaar/openbazaar-desktop/pull/180#issuecomment-266172636)
- hides sections of the listing modal that haven't been implemented yet

### CODE REVIEW

**Comment by jjeffryes** [comment]
When I try this PR, it can't load profile data. 

image

**Comment by rmisio** [comment]
@jjeffryes I think you're going to have to wipe your DB. I noticed some weird behavior too and after a wipe (or two) haven't had any problems.

**Comment by jjeffryes** [comment]
No good. Still dead in the water after 2 db wipes.

**Comment by jjeffryes** [comment]
Also, if I switch back to master, everything works fine, so it looks like there's an issue in the PR.

**Comment by jjeffryes** [comment]
Turned out to just be a case of my server git was off. Everything is working as intended.

**Pull request merged**
