### PR TITLE
[WIP] Share this store on Twitter

### PR DESCRIPTION
**Pull request by hoffmabc**
Twitter Share Button on Home tab

image

### CODE REVIEW

**Comment by jjeffryes** [comment]
Do we want to design something more robust, with support for multiple social networks, like we had in v1?

@morebrownies ?

**Comment by morebrownies** [comment]
I think that's probably a good idea to put this task through a design phase @jjeffryes and @hoffmabc. The `information` section on the user `home` page is probably very rarely viewed. I would imagine we would want to expose the share button(s) in areas that get more eye traffic? 

For example, I would imagine the most valuable placement for share buttons would be somewhere high up on the listing detail screens.  Users visit listing details a lot more frequently and are more likely to share a listing than a user's `home` page.

**Comment by hoffmabc** [comment]
- I think a design phase would be fine since I'm springing this on you guys. I'm trying to pitch out some easy little tweaks to inspire a few updates here and there when I have a chance.
- The home page is rarely shared, which is true, but the idea is that there is literally nowhere to share out a page via button at the moment, which kind of stinks. I'm supportive of moving it higher up somewhere. 
- I think we probably need to offer both store sharing and listing sharing. I see check out my store way more often than check out my product. I think both are probably needed.

**Comment by christroutner** [comment]
Re: "there is literally nowhere to share out a page via button at the moment"

Have you guys checked out the app on a 1920x1080 monitor? The OB client does not scale to fit different resolutions.  There is a tone of wasted space, and monitor resolution is only going up. I do web site design, which is why I have a laptop such very high definition. 

Next time you're doing some road-mapping, you should checkout Bootstrap 3 or 4, and talk about how you'll approach a mobile-first design. Changes could be adapted iteratively to the Backbone templates over the course of a year.

That would kill two birds with one stone by also moving you towards a smartphone friendly interface. A smartphone UI is a topic I want to talk about with you all further, maybe on the next dev call?

**Comment by jjeffryes** [comment]
@christroutner we know the app isn't responsive. The CSS framework we wrote is responsive ready, we just haven't added any responsive designs yet.

**Comment by rmisio** [comment]
@hoffmabc Since this is been kind of dormant for a while, can we close this PR and potentially re-vive it after we go through the aforementioned design phase?

**Comment by hoffmabc** [comment]
I think you misspelled never. Sure that’s fine.

**Pull request closed without merging**
