### PR TITLE
add contributors

### PR DESCRIPTION
**Pull request by jashot7**
Added myself and MG to the list to keep it up to date in the app.

Let me know if I should add others or if you have any tweaks/suggestions.

### CODE REVIEW

**Comment by jjeffryes** [comment]
@jashot7 add Monique please.

**Comment by jjeffryes** [comment]
I think there are some other people that have contributed code, but I'm not sure what a fast way to find them is.

**Comment by jashot7** [comment]
@jjeffryes Added Monique and the mobile contractors Daniel Zheng and Jiting Song. 

@drwasho Can you just confirm those names are correct?

**Comment by jashot7** [comment]
I do believe this is now ready for merge, @jjeffryes or @rmisio.

**Comment by rmisio** [comment]
@jjeffryes let's merge this bad boy!

**Pull request merged**
