### PR TITLE
Make modal height flexible

### PR DESCRIPTION
**Pull request by jjeffryes**
Makes the modal heights change with the window height.

### CODE REVIEW

**Comment by rmisio** [comment]
There's a couple issues with this approach:

1.)  I don't think all modal should have this type of flexible height. For example, here's one that shouldn't:

image

I'm thinking maybe we make the default the old way and then make the flexible heigh opt in via a class (it could be vice versa as well).

2.) I would think even on flexible height modals, we'd still want some max height. Otherwise if someone has a really large monitor, the modal is always going to take up 90% (or whatever) of the screen space and there would potentially be a lot of white space on the modal.

=====

Another thing I wanted to point out is with this approach, if the modal content is larger than the viewport could support (large modal and/or small monitor), we're not going to get the scrollbars on the overlay (like Mike's fiddle example showed). Instead, each modal will still need to be able to have an inner scroll bar to account for this case. For example:

image

=====

I think we need to think through this approach. Because the idea was that this was supposed to be an easy bridge between fixed height modals and the real solution Mike wants. But, it's fraught with problem. I think we need to think about whether it's better to think more about this approach and patch the patch, revert back to the previous way (fixed height modals) or bite the bullet and take the scope hit involved with transitioning to the real way Mike wants.

@morebrownies what do you think? Maybe you want to play around with this branch and see what you think?

**Comment by jjeffryes** [comment]
This has been redone to align modals with the "modalTop" class to the top of the window, below the navBar, and set their height to expand with their content. The settings modal has a minimum height, we may want to move that to apply to all modalTop modals. 

The maximum height is set to fill the area under the navBar, minus a margin at the top and bottom. If the modal content is bigger than that, an internal scrollbar will appear in the modal.

This PR doesn't change the settings save button, it's still a single button for all the tabs, but it is now positioned at the bottom of the content, so it will need to be scrolled to if the content is larger than the modal maximum height.

**Comment by jjeffryes** [comment]
@morebrownies take a look at this when you have a minute, and see what you think.

**Comment by morebrownies** [comment]
@jjeffryes Is there a specific modal I can trigger to see the height change?

**Comment by jjeffryes** [comment]
@morebrownies open the settings modal, and switch between the general, page and address tabs. Each one has a different height.

**Pull request merged**
