### PR TITLE
1707

### LINKED ISSUE #1707: Missing dispute Resolve button for ZEC orders
Brief Description: When a moderator views a dispute for an order using ZEC, a Resolve button is missing to proceed the dispute forward.

Operating System (OS and version): N/A
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: N/A

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Create a moderated order with ZEC as the payment
2. Either buyer or seller can dispute the order.
3. The moderator opens the dispute and finds the missing button in the UI.

Observed Behavior:
Resolve button is missing

Expected Behavior:
Expected the Resolve button to be present.

### PR DESCRIPTION
**Pull request by rmisio**
closes #1707

### CODE REVIEW

**Comment by pinheadmz** [comment]
Running this branch, trying to close the dispute in question. Still not getting the resolve button, and this error in Electron JS console:
```
Summary.js? [sm]:817 Uncaught TypeError: Cannot read property 'isCase' of undefined
    at _class.renderDisputeStartedView (Summary.js? [sm]:879)
    at Summary.js? [sm]:1059
    at Array.forEach (<anonymous>)
    at _class.renderSubSections (Summary.js? [sm]:1061)
    at Summary.js? [sm]:375
    at sendBackTmpl (loadTemplate.js? [sm]:4)
    at loadTemplate (loadTemplate.js? [sm]:17)
    at _class.render (Summary.js? [sm]:1046)
    at _class.selectTab (OrderDetail.js? [sm]:191)
    at OrderDetail.js? [sm]:463
﻿```

Note, I did not update my server (even though running this branch of desktop told me to). Server is still 0.13 not 0.13.1

**Comment by rmisio** [comment]
@pinheadmz Try now. I had a typo in there.

**Comment by pinheadmz** [comment]
Ok now I'm seeing the button, but clicking it isn't doing anything (nothing in console either)

**Comment by rmisio** [comment]
@pinheadmz you want to try now?

Thanks for the help on this. I'm cutting a corner by not testing myself... but the data set-up is a bit of a pain.

**Comment by pinheadmz** [comment]
Success!!!! Happy customers! Great job, thanks
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by rmisio** [comment]
@pinheadmz Hooray! I'm glad it worked.

I do gotta say though, you probably don't want to run live orders through non-released code. There might be some bugs there that might cause some unwanted results.

**Comment by pinheadmz** [comment]
Yeah I know, but this was a small order and both parties were already considering the tx abandoned, waiting for vendor 45-day timeout, I'm happy to make the occasional reckless move to progress development :-)

**Comment by jjeffryes** [comment]
@rmisio for orders with a timeout, can we avoid showing double resolve dispute buttons?

image

**Comment by rmisio** [comment]
> for orders with a timeout, can we avoid showing double resolve dispute buttons?

ok, should be in now.

**Comment by jjeffryes** [comment]
@rmisio can you fix the lint error in Summary.js?

**Pull request merged**
