### PR TITLE
[WIP] Auto-Update Code and IPC Messages

### PR DESCRIPTION
**Pull request by hoffmabc**
This is a working branch for code related to the auto-updating feature for the application. The objective would be to incorporate this with @rmisio refactoring of main.js and anything else that will be changed before release.

Changes:
- [x] Add autoUpdater code for OS X 
- [ ] Add autoUpdater code for Windows
- [x] Send IPC calls to the rendering process instead of brute-forcing console.log and CSS manipulation in that process
- [ ] Handle IPC messages in the views and display update alerts to user
- [x] Set up squirrel server for 2.0
- [x] Install SSL certificate and DNS for squirrel server

### CODE REVIEW

**Comment by jjeffryes** [comment]
Reminder to leave a message when closing a PR. ;)

**Comment by rmisio** [comment]
> Reminder to leave a message when closing a PR. ;)

uh-oh!

image

**Comment by hoffmabc** [comment]
I opened it again so nice try.

**Comment by hoffmabc** [comment]
https://github.com/OpenBazaar/openbazaar-desktop/pull/170

**Comment by hoffmabc** [comment]
Oh weird...I guess when you have protected branches it doesn't allow to update a PR.

**Pull request closed without merging**
