### PR TITLE
Adjust Listing Card Styles

### PR DESCRIPTION
**Pull request by jjeffryes**
This addresses some layout issues noticed in #1246

### CODE REVIEW

**Comment by morebrownies** [comment]
Looks good 👍

**Comment by morebrownies** [comment]
@jjeffryes can you make sure to link the `learn more` links to http://ob1.io/verified-moderators.html

**Comment by jjeffryes** [comment]
@morebrownies the links are actually up to Tyler, they're sent from the search provider.

Attn: @tyler-smith can you update the link to http://ob1.io/verified-moderators.html ?

**Comment by rmisio** [comment]
@jjeffryes Clicking on Learn More in the verified mod tip on a listing card not only opens up the link in the browser, it also registers a click of the listing card and opens up the listing detail. Can you fix it so the latter doesn't happen?

**Comment by rmisio** [comment]
Aside from comment above, this one LGTM.

**Comment by rmisio** [comment]
We have styling issue in the verified mods box on the mod detail view:

image

**Comment by hoffmabc** [comment]
I'm not seeing that on rc2.
image

**Comment by rmisio** [comment]
@hoffmabc It happens for an unverified mod. You're looking at a verified one.

**Comment by jjeffryes** [comment]
> We have styling issue in the verified mods box on the mod detail view:

That was fixed in a different PR that has been merged.

**Pull request merged**
