### PR TITLE
Dispute payout precision

### LINKED ISSUE #1841: Eth-Precision: Moderator Fee in Settings Shown as USD when it is ETH
The server is returning amountCurrency:{ code: "ETH", divisibility: 8}, but in settings/moderation the moderator's fixed fee is showing USD as the currency.

This requires the user to set their currency back to ETH before saving.

### PR DESCRIPTION
**Pull request by rmisio**
Implements conversions from string based integers to numbers for the dispute resolution section of  order data.

closes #1841

### CODE REVIEW

**Comment by jjeffryes** [comment]
With the latest changes, I get a "The moderation settings were not saved." error from the client when I try to save moderation settings with a percentage fee.

**Comment by jjeffryes** [comment]
In the save.fail on settings/moderation.js, I'm seeing 
```
message: "Unexpected end of JSON input"
stack: "SyntaxError: Unexpected end of JSON input↵    at parse (<anonymous>)↵    at ajaxConvert (/Users/jjeffryes/openbazaar-desktop-mast
```

**Comment by jjeffryes** [comment]
@rmisio is this ready for re-review?

**Comment by rmisio** [comment]
@jjeffryes Probably not because there are still ob-go bugs that need to be resolved. I don't think they'll require any client action, but it's still a potentially broken experience until they are fixed.

**Comment by rmisio** [comment]
@jjeffryes I think you could re-test this one since it looks like the dependent ob-go bugs have presumedly had fixes merged.

**Comment by jjeffryes** [comment]
This looks good on re-testing.

**Pull request merged**
