### PR TITLE
added new splash screen art, logos, window installers, etc

### LINKED ISSUE #803: Improve the design of the installation splash screen
Currently it looks something like this

screen_shot_2017-09-06_at_9 48 54_pm

### LINKED ISSUE #811: Installation processing spinner needs to be updated
We're currently using the same one from 1.0

https://github.com/OpenBazaar/openbazaar-desktop/blob/master/imgs/windows-loading.gif

### PR DESCRIPTION
**Pull request by morebrownies**
Closes #803 
Closes #811

### CODE REVIEW

**Comment by morebrownies** [comment]
I have no idea if it is possible to test these changes locally. I believe we'll need to incorporate them into the next build in order to see them in action. 

Does that sound right @hoffmabc?

**Comment by jjeffryes** [comment]
> I have no idea if it is possible to test these changes locally. I believe we'll need to incorporate them into the next build in order to see them in action.

I think you're right, the only way to test these is in a build. @hoffmabc ?

**Comment by hoffmabc** [comment]
I'll test it now.

**Comment by hoffmabc** [comment]
I'll post the updated installers in slack to test out

**Pull request merged**
