### PR TITLE
Profile schema refactor

### LINKED ISSUE #394: Profile schema refactor
Changes and discussion is here https://github.com/OpenBazaar/openbazaar-go/pull/388

### PR DESCRIPTION
**Pull request by rmisio**
closes #394

The server Profile schema changed as follows:
https://github.com/OpenBazaar/openbazaar-go/pull/388/files#diff-eabc92361d47b20a039e698c17ca1849

This is a client PR to account for those changes. The areas in the UI effected by the schema change are numerous. Some key areas are:
- The user page, primarily the Home tab.
- The Page tab of settings.
- The Moderation tab of settings.

JIRA ticket:
https://ob1company.atlassian.net/browse/OB-256

This needs to be tested with the following code from the server:
https://github.com/OpenBazaar/openbazaar-go/pull/388

This also requires that you wipe your DB.

### CODE REVIEW

**Comment by jjeffryes** [comment]
This looks good to me. @morebrownies and/or @hoffmabc can you test it as well?

Just as an FYI, I've added a task to the backlog to add the social media accounts interface to the settings profile tab. Currently there isn't a way in the UI to actually add any social media accounts.

**Comment by hoffmabc** [comment]
Yep will test now

**Comment by hoffmabc** [comment]
I blew away my DB and tried and I get this.
image

**Comment by rmisio** [comment]
@hoffmabc you need to make sure you are running this server:
OpenBazaar/openbazaar-go#388

**Comment by hoffmabc** [comment]
Thanks @rmisio.

What does this spinner indicate?
image

**Comment by hoffmabc** [comment]
How come GUID is just floating here with no value? And didn't we agree to move to Peer ID? 
image

**Comment by hoffmabc** [comment]
Also how come Email address is not clickable and a mailto: link? Did we purposely decide not to do that?

**Comment by hoffmabc** [comment]
That might be a question for @morebrownies

**Comment by morebrownies** [comment]
I'll review shortly. Making email clickable would be fine

**Comment by rmisio** [comment]
@morebrownies @hoffmabc Could we please focus on stuff specifically related to the profile schema refactor and log bugs / JIRA stories for anything else?

**Comment by hoffmabc** [comment]
I thought this was part of it (the email link) @rmisio sorry.

**Comment by rmisio** [comment]
@hoffmabc re: chat spinner. That indicates that a previous page of chat messages are being fetched.

**Comment by hoffmabc** [comment]
A JIRA link would have been nice as well since I didn't even know it existed until now.

**Comment by rmisio** [comment]
> How come GUID is just floating here with no value?

Good catch! That was a bug that I just fixed.

> And didn't we agree to move to Peer ID?

I don't know anything about that, but if that's the case, I think we should get a bug / JIRA story and work on that separate from this. There's probably a lot of places in the UI, the term GUID is being used.

**Comment by hoffmabc** [comment]
OK will file another issue on the GUID thing.

**Comment by morebrownies** [comment]
I tested adding a name, short desc, long desc, location, website, email, avatar, cover photo and it all seemed to work as expected.

My guid displays correctly too

screenshot 2017-03-22 10 35 23

**Pull request merged**
