### PR TITLE
1124

### LINKED ISSUE #1124: Support Link Added to Client
Link to https://openbazaar.org/support within the app under "Help" in the top menu as well as within "About OpenBazaar."

### PR DESCRIPTION
**Pull request by rmisio**
closes #1124

### CODE REVIEW

**Comment by jjeffryes** [comment]
This looks good to me.

@morebrownies would it be even more clear if there was a Help link under the About OpenBazaar link in the page nav menu? 

Right how you'd have to open the About modal first before finding a the help tab.

**Comment by morebrownies** [comment]
Yeah I suggested that in issue #1124

**Comment by morebrownies** [comment]
@rmisio can you make sure to add the help link into the nav bar? See #1124 for more info.

**Comment by jjeffryes** [comment]
@morebrownies I submitted a PR for the help link. #1133

**Pull request merged**
