### PR TITLE
Alphabetize translation crypto curs

### PR DESCRIPTION
**Pull request by rmisio**
This adjusts the `getCryptoData` script so that the crypto currencies it outputs to the translation file are alphabetized by cur code.

### CODE REVIEW

**Comment by jjeffryes** [comment]
```
{
    "notifications": [
        {
            "notification": {
                "buyer": "QmSxrDKfmZgJmg9bZYsgiCyAZXkPkmvv7qJxMZBQ1WY7eL",
                "notificationId": "QmNrt7p642f9BYxXQp1TDtRoGDaAxm31gSbHPm2iCugj3h",
                "orderId": "QmbMnkBfoJQkAt8p819wroXUnsjuZ3CVQJAfp8sVJFevRj",
                "otherPartyHandle": "",
                "otherPartyId": "QmcqJmESoxobiSJ4yppRmd4FAfxzgs2UTjBBqwJtjftKbC",
                "thumbnail": {
                    "small": "zb2rhn7ndzjfu9CXJXUB52aCTajzMUGRLEGBvTWDWBNphdMZb",
                    "tiny": "zb2rhfmZuVzBybRNezLnJm1SJt9rBPE7wtcKisX8VHEhQDntk"
                },
                "type": "disputeAccepted"
            },
            "read": true,
            "timestamp": "2018-07-25T11:34:57-07:00",
            "type": "disputeAccepted"
        },
        {
            "notification": {
                "buyer": "QmSxrDKfmZgJmg9bZYsgiCyAZXkPkmvv7qJxMZBQ1WY7eL",
                "notificationId": "QmdJ9TYUAinj5q2T4d491W9Lm89G6cdgxfR7PUFcrRUUjJ",
                "orderId": "QmbMnkBfoJQkAt8p819wroXUnsjuZ3CVQJAfp8sVJFevRj",
                "otherPartyHandle": "",
                "otherPartyId": "QmcqJmESoxobiSJ4yppRmd4FAfxzgs2UTjBBqwJtjftKbC",
                "thumbnail": {
                    "small": "zb2rhn7ndzjfu9CXJXUB52aCTajzMUGRLEGBvTWDWBNphdMZb",
                    "tiny": "zb2rhfmZuVzBybRNezLnJm1SJt9rBPE7wtcKisX8VHEhQDntk"
                },
                "type": "disputeClose"
            },
            "read": true,
            "timestamp": "2018-07-25T11:34:45-07:00",
            "type": "disputeClose"
        },
        {
            "notification": {
                "buyer": "QmSxrDKfmZgJmg9bZYsgiCyAZXkPkmvv7qJxMZBQ1WY7eL",
                "disputeeHandle": "",
                "disputeeId": "QmSxrDKfmZgJmg9bZYsgiCyAZXkPkmvv7qJxMZBQ1WY7eL",
                "disputerHandle": "",
                "disputerId": "QmcqJmESoxobiSJ4yppRmd4FAfxzgs2UTjBBqwJtjftKbC",
                "notificationId": "QmUr41icEy6TZGb6ugs9f8iFFYh3mj85qMjLN9BPjraocS",
                "orderId": "QmbMnkBfoJQkAt8p819wroXUnsjuZ3CVQJAfp8sVJFevRj",
                "thumbnail": {
                    "small": "zb2rhn7ndzjfu9CXJXUB52aCTajzMUGRLEGBvTWDWBNphdMZb",
                    "tiny": "zb2rhfmZuVzBybRNezLnJm1SJt9rBPE7wtcKisX8VHEhQDntk"
                },
                "type": "disputeOpen"
            },
            "read": true,
            "timestamp": "2018-07-25T11:34:13-07:00",
            "type": "disputeOpen"
        },
        {
            "notification": {
                "notificationId": "QmeNjem3z6CyDAH9nzpd4T8qcgqoXkKoPJSiBfJmhTDgM4",
                "orderId": "QmbMnkBfoJQkAt8p819wroXUnsjuZ3CVQJAfp8sVJFevRj",
                "thumbnail": {
                    "small": "zb2rhn7ndzjfu9CXJXUB52aCTajzMUGRLEGBvTWDWBNphdMZb",
                    "tiny": "zb2rhfmZuVzBybRNezLnJm1SJt9rBPE7wtcKisX8VHEhQDntk"
                },
                "type": "fulfillment",
                "vendorHandle": "",
                "vendorId": "QmcqJmESoxobiSJ4yppRmd4FAfxzgs2UTjBBqwJtjftKbC"
            },
            "read": true,
            "timestamp": "2018-07-25T11:34:02-07:00",
            "type": "fulfillment"
        }
    ],
    "total": 79,
    "unread": 0
}
```

The complete HTML for the notification:
```
<div class="listItem notificationListItem js-notificationListItem clrBr ">
  <div class="unreadBorder clrBAtt1"></div>
  <div class="flexVCent gutterHSm pad">
    <div class="thumbCol disc clrBr2 clrSh1 flexNoShrink listingImage" style="background-image: url(http://localhost:4002/ob/images/zb2rhfmZuVzBybRNezLnJm1SJt9rBPE7wtcKisX8VHEhQDntk), url(../imgs/defaultItem.png)"></div>
    <div class="flexExpand">
      <div class="rowTn clamp2 notifMsg">The dispute with <a class="clrTEm" href="#undefined">QmcqJmES…</a> has been finalized.</div>
      <div class="clrT2 tx6">4 hours ago</div>
    </div>
  </div>
</div>
```

**Comment by jjeffryes** [comment]
This is happening with all the dispute notifications in the JSON above, but not the fulfillment notification.

**Comment by rmisio** [comment]
@jjeffryes I think you pasted that in the wrong issue.

**Comment by jjeffryes** [comment]
Well, heck. You're right. Too many tabs open.

**Pull request merged**
