### PR TITLE
Updated window controls (fixes #141)

### LINKED ISSUE #141: Mac window management controls are a bit off from the true native controls
**To do**

- Update colors
- Increase spacing
- Add border
- Show icons within the circles on hover

**Current**
screenshot 2016-12-02 14 14 34

**Native**
screenshot 2016-12-02 14 14 40

### PR DESCRIPTION
**Pull request by morebrownies**
This makes the Mac style window controls match the native experience more closely (fixes #141).

@jjeffryes there's one thing I wasn't able to figure out... On a native Mac window, when you hover any circle, all 3 icons display at the same time (as pictured below). 

screenshot 2016-12-02 17 07 56

I wasn't able to figure out how to get this working in OB. If it's an easy change, it would be nice to layer it in.

### CODE REVIEW

**Comment by morebrownies** [comment]
I think something like this should get the icons working

```
    .macStyleWindowControls:hover ~ .windowControls a span {
      visibility: visible;
    }
```

But I may be messing up the syntax in scss.

**Comment by jjeffryes** [comment]
@morebrownies the code looks correct to me, and on my Mac VM only the button I'm hovering over changes.

**Comment by morebrownies** [comment]
Right, but on a native Mac window, when you hover any window control button, all 3 icons should display at the same time. That's what I'm trying to get working, but can't seem to figure out the correct scss for it.

**Comment by jjeffryes** [comment]
Oh, I see. I thought you meant the other way around. I'll patch it.

**Comment by morebrownies** [comment]
@jjeffryes I'm not seeing any updates here. Are you sure you pushed your changes?

**Comment by morebrownies** [comment]
Ok @jjeffryes your PR looks good. I merged it into this PR.

**Pull request merged**
