### PR TITLE
More listings

### LINKED ISSUE #344: Display "More listings by..." section at the bottom of the listing detail screen
It would be nice to display additional listings sold by the vendor at the bottom of the listing detail screen. This is a good opportunity to help people discover more and keep them engaged in the shopping process. 

Not urgent, but if it's relatively low effort, it would be worth adding. 

screenshot 2017-01-31 15 46 22

### PR DESCRIPTION
**Pull request by jjeffryes**
This adds a more listings section to the bottom of each listings details modal. 

Clicking on a listing card in the more listings section will open a new modal and close the parent modal.

Up to 8 listing cards are shown. If none have loaded, or the user doesn't have other listings, the more listings section isn't shown.

Closes #344

### CODE REVIEW

**Comment by morebrownies** [comment]
Thank you for adding this @jjeffryes

**Comment by morebrownies** [comment]
Looks good to me @jjeffryes

**Comment by morebrownies** [comment]
There seems to be an issue with the back button. I have to hit back twice after clicking a listing within "More by [Name]".

**Comment by morebrownies** [comment]
It would be better to show 8 random listings @rmisio.

**Comment by rmisio** [comment]
> It would be better to show 8 random listings @rmisio.

Cool, I'll work that in. Eventually, if we're feeling really ambitious, we could work it into the randomizer where more weight is given to listing with the same category or tags... but, for now, I'll leave that as a very stretchy goal at best.

**Comment by morebrownies** [comment]
> Cool, I'll work that in. Eventually, if we're feeling really ambitious, we could work it into the randomizer where more weight is given to listings with the same category or tags... but, for now, I'll leave that as a very stretchy goal at best.

Sounds good!

**Comment by jashot7** [comment]
@rmisio @jjeffryes I'm getting the same issue @morebrownies is getting with the back button needing to be pressed twice.

When pressing on one of the results in 'more by', the user navigates to the listing, but the URL displays the store URL rather than that for the specific listing. 

screen shot 2018-08-27 at 4 38 16 pm

Then, when the user hits the back button - the page reloads that same listing, but with the correct URL.

screen shot 2018-08-27 at 4 38 36 pm

**Comment by rmisio** [comment]
closing in liu of #1544

**Pull request closed without merging**
