### PR TITLE
Changing order of items in menu + link in first  menu item + make address name bold

### LINKED ISSUE #596: Make Address Name Bold
Name in Shipping Addresses page should be displayed in **bold**
bold name

### LINKED ISSUE #655: First menu item text is not clickable
v.2.0.6 w7 64 bits

Page's name menu item is not clickable. I believe it should link to "Home" page.
menu item

### LINKED ISSUE #1449: Inconsistent ordering of transactions items
Transactions page: Sales, Purchases, Cases
Menu: Purchases, Sales, Cases
image

### PR DESCRIPTION
**Pull request by rhcastilhos**
closes #1449
closes #655
closes #596

### CODE REVIEW

**Comment by rmisio** [comment]
@rhcastilhos This is looking pretty good. I'm just waiting on our UX lead to approve a couple of these to see if that's what we want.

In general, especially if things aren't approved, it's probably better to make a seperate PR for each issue.

Thanks for the help!

**Comment by jjeffryes** [comment]
@morebrownies did you approve of all the UX changes here?

**Comment by rmisio** [comment]
> did you approve of all the UX changes here?

@jjeffryes He did, in the individual issues.

**Comment by morebrownies** [comment]
I didn't get a chance to review the PR yet, but if it coded as described in the Issues, then lgtm 👍

**Pull request merged**
